{% set name = "peft" %}
{% set version = "0.15.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/peft-{{ version }}.tar.gz
  sha256: 7059029f4d42a092ded1aa117dd366a46084aef638bdd593f6ab0195d5427fcd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - accelerate >=0.21.0
    - huggingface_hub >=0.25.0
    - numpy >=1.17
    - packaging >=20.0
    - psutil
    - python >={{ python_min }}
    - pytorch >=1.13.0
    - pyyaml
    - safetensors
    - transformers >=4.18.0
    - tqdm

test:
  imports:
    - peft
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/peft
  doc_url: https://huggingface.co/docs/peft
  dev_url: https://github.com/huggingface/peft
  summary: Parameter-Efficient Fine-Tuning (PEFT)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
