{% set name = "peft" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/peft-{{ version }}.tar.gz
  sha256: 0e0cbd40ebdf5fe4ea79f255880d02f96712d18899509369a2cc5768ad46d672

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - accelerate >=0.21.0
    - huggingface_hub >=0.17.0
    - numpy >=1.17
    - packaging >=20.0
    - psutil
    - python >=3.8
    - pytorch >=1.13.0
    - pyyaml
    - safetensors
    - transformers >=4.18.0
    - tqdm

test:
  imports:
    - peft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/peft
  doc_url: https://huggingface.co/docs/peft
  dev_url: https://github.com/huggingface/peft
  summary: Parameter-Efficient Fine-Tuning (PEFT)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
