{% set name = "peft" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/peft-{{ version }}.tar.gz
  sha256: 6c381208f705cd38f2cc91dc2943ac4df2615680bd75d7320d010f8f2e48e65d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.17
    - packaging >=20.0
    - psutil
    - pyyaml
    - pytorch >=1.13.0
    - transformers
    - accelerate

test:
  imports:
    - peft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/peft
  summary: Parameter-Efficient Fine-Tuning (PEFT)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
